@startwbs

<style>
node {
    Padding 12
    Margin 3
    HorizontalAlignment center
    MaximumWidth 100
}

rootNode {
    LineThickness 1.0
}

leafNode {
    Padding 3
}

</style>

*[#darkorange] CityTwin
**[#deeppink] Mainstay Nodes
***[#mediumpurple] Receive information from Resource nodes modeling sensors
***[#mediumpurple] Communicate information to Resource nodes modeling actuators
***[#mediumpurple] Detect malfunctions in Resource nodes
***[#mediumpurple] Detect malfunctions in other Mainstay nodes
***[#mediumpurple] Save information by contacting the persistence service
***[#mediumpurple] No need to know the types of Resource nodes in advance
**[#deeppink] Resource Nodes
***[#mediumpurple] Reference a Mainstay node to obtain or communicate information
***[#mediumpurple] Can be added or removed in real-time
**[#deeppink] Data Persistence Service
***[#mediumpurple] Persistently save the state of Mainstay nodes
***[#mediumpurple] Persistently save the state of Resource nodes
**[#deeppink] Fault Tolerance
***[#mediumpurple] Malfunction of a node should not compromise the system's operation
**[#deeppink] Modularity
***[#mediumpurple] Introduce new modules without modifying existing components
**[#deeppink] Specific Modules for Resource Nodes
***[#mediumpurple] Acid Rain Detection Sensor
***[#mediumpurple] Air Quality Analysis Sensor
***[#mediumpurple] Noise Pollution Detection Sensor
***[#mediumpurple] River Water Level Detection Module
@endwbs
